#!/usr/bin/env node

/**
 * mcp-shell-server setup wizard
 * ─────────────────────────────────────────────
 * Interactive (no args) or CLI-based setup.
 * Generates .env, client config JSON, Caddyfile,
 * PM2 ecosystem, and systemd service file.
 *
 * Usage:
 *   node setup.js                          # interactive
 *   node setup.js --help                   # show CLI flags
 *   node setup.js --port 9876 --domain example.com
 */

import { createInterface } from "node:readline/promises";
import { randomBytes } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { execSync } from "node:child_process";
import { platform, hostname } from "node:os";
import { stdin as input, stdout as output, argv, exit } from "node:process";

// ──────────────────────────────────────────────
//  Terminal helpers
// ──────────────────────────────────────────────

const IS_WIN   = platform() === "win32";
const IS_LINUX = platform() === "linux";

function bold(s)   { return `\x1b[1m${s}\x1b[22m`; }
function green(s)  { return `\x1b[32m${s}\x1b[39m`; }
function cyan(s)   { return `\x1b[36m${s}\x1b[39m`; }
function yellow(s) { return `\x1b[33m${s}\x1b[39m`; }
function dim(s)    { return `\x1b[2m${s}\x1b[22m`; }
function red(s)    { return `\x1b[31m${s}\x1b[39m`; }

// ──────────────────────────────────────────────
//  Defaults
// ──────────────────────────────────────────────

const DEFAULTS = {
  port:    "13579",
  workdir: process.cwd(),
  timeout: "30000",
  token:   "",
  domain:  "",
};

// ──────────────────────────────────────────────
//  CLI arg parser
// ──────────────────────────────────────────────

function parseArgs(argv) {
  const args = argv.slice(2);
  const opts = { ...DEFAULTS };
  let interactive = args.length === 0;

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case "--help":
      case "-h":
        printHelp();
        exit(0);
      case "--port":
      case "-p":
        opts.port = args[++i];
        interactive = false;
        break;
      case "--workdir":
      case "-w":
        opts.workdir = resolve(args[++i]);
        interactive = false;
        break;
      case "--timeout":
      case "-t":
        opts.timeout = args[++i];
        interactive = false;
        break;
      case "--token":
        opts.token = args[++i];
        interactive = false;
        break;
      case "--domain":
      case "-d":
        opts.domain = args[++i];
        interactive = false;
        break;
      case "--no-pm2":
        opts.noPm2 = true;
        interactive = false;
        break;
      default:
        console.error(`Unknown flag: ${args[i]}\n`);
        printHelp();
        exit(1);
    }
  }

  return { ...opts, interactive };
}

function printHelp() {
  console.log(`
  ${bold("meowshell — Setup")}

  ${dim("Interactive mode (default):")}
    node setup.js

  ${dim("CLI mode:")}
    node setup.js [flags]

  ${bold("Flags:")}
    ${cyan("-p, --port <port>")}         Server port ${dim(`(default: ${DEFAULTS.port})`)}
    ${cyan("-w, --workdir <path>")}      Working directory ${dim(`(default: cwd)`)}
    ${cyan("-t, --timeout <ms>")}        Command timeout ${dim(`(default: ${DEFAULTS.timeout})`)}
    ${cyan("--token <token>")}           Bearer token ${dim("(default: auto-generate)")}
    ${cyan("-d, --domain <domain>")}     Domain for Caddy auto-HTTPS ${dim("(optional)")}
    ${cyan("--no-pm2")}                  Skip PM2 setup
    ${cyan("-h, --help")}                Show this help
`);
}

// ──────────────────────────────────────────────
//  Helpers
// ──────────────────────────────────────────────

function generateToken(length = 48) {
  return randomBytes(length).toString("hex");
}

async function ask(rl, question, defaultValue) {
  const defaultPart = defaultValue != null ? ` ${dim(`[${defaultValue}]`)}` : "";
  const answer = await rl.question(`${question}${defaultPart}: `);
  return answer.trim() || (defaultValue ?? "");
}

async function askConfirm(rl, question, defaultYes = true) {
  const hint = defaultYes ? "Y/n" : "y/N";
  const answer = await rl.question(`${question} ${dim(`(${hint})`)}: `);
  const trimmed = answer.trim().toLowerCase();
  if (trimmed === "") return defaultYes;
  return trimmed === "y" || trimmed === "yes";
}

async function tryExec(cmd, opts = {}) {
  try {
    execSync(cmd, { stdio: "pipe", timeout: 30000, ...opts });
    return true;
  } catch {
    return false;
  }
}

// ──────────────────────────────────────────────
//  Config generation
// ──────────────────────────────────────────────

function buildEnv(config) {
  return `# meowshell Configuration
# Generated by setup.js — ${new Date().toISOString()}
MCP_TOKEN=${config.token}
MCP_PORT=${config.port}
MCP_WORKDIR=${config.workdir}
MCP_TIMEOUT=${config.timeout}
`;
}

function buildClientConfig(config) {
  const protocol = config.domain ? "https" : "http";
  const host     = config.domain || "localhost";
  const url      = `${protocol}://${host}:${config.port}/mcp`;

  return {
    mcpServers: {
      "my-server": {
        type: "url",
        url,
        headers: {
          Authorization: `Bearer ${config.token}`,
        },
      },
    },
  };
}

function buildCaddyfile(config) {
  return `${config.domain} {
\treverse_proxy localhost:${config.port}
}
`;
}

function buildEcosystem(config) {
  const serverPath = resolve(config.workdir, "meowshell.js");
  return `module.exports = {
  apps: [{
    name: "mcp-shell-server",
    script: ${JSON.stringify(serverPath)},
    env: {
      MCP_TOKEN: ${JSON.stringify(config.token)},
      MCP_PORT: ${JSON.stringify(config.port)},
      MCP_WORKDIR: ${JSON.stringify(config.workdir)},
      MCP_TIMEOUT: ${JSON.stringify(config.timeout)},
    },
    watch: false,
    max_memory_restart: "200M",
  }]
};
`;
}

function buildSystemdService(config) {
  const serverPath = resolve(config.workdir, "meowshell.js");
  const user = process.env.USER || process.env.USERNAME || "root";
  return `[Unit]
Description=meowshell
After=network.target

[Service]
Type=simple
User=${user}
WorkingDirectory=${config.workdir}
Environment=MCP_TOKEN=${config.token}
Environment=MCP_PORT=${config.port}
Environment=MCP_WORKDIR=${config.workdir}
Environment=MCP_TIMEOUT=${config.timeout}
ExecStart=${process.execPath} ${serverPath}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
`;
}

// ──────────────────────────────────────────────
//  File writer
// ──────────────────────────────────────────────

async function writeFiles(config, baseDir) {
  const files = [];

  // .env
  const envPath = resolve(baseDir, ".env");
  await writeFile(envPath, buildEnv(config), "utf-8");
  files.push({ name: ".env", path: envPath });

  // mcp-client-config.json
  const clientConfig = buildClientConfig(config);
  const configPath = resolve(baseDir, "mcp-client-config.json");
  await writeFile(configPath, JSON.stringify(clientConfig, null, 2), "utf-8");
  files.push({ name: "mcp-client-config.json", path: configPath });

  // Caddyfile (only if domain specified)
  if (config.domain) {
    const caddyPath = resolve(baseDir, "Caddyfile");
    await writeFile(caddyPath, buildCaddyfile(config), "utf-8");
    files.push({ name: "Caddyfile", path: caddyPath });
  }

  return { files, clientConfig };
}

// ──────────────────────────────────────────────
//  Interactive mode
// ──────────────────────────────────────────────

async function interactiveSetup() {
  const rl = createInterface({ input, output });

  console.log(`
  ╭──────────────────────────────────────────────╮
  │  ${bold("🐱  meowshell — Setup Wizard")}        │
  │                                              │
  │  Let's get your server purring in under 60s. │
  ╰──────────────────────────────────────────────╯
  `);

  const config = { ...DEFAULTS };

  config.port    = await ask(rl, "Port", DEFAULTS.port);
  config.workdir = resolve(await ask(rl, "Working directory", DEFAULTS.workdir));
  config.timeout = await ask(rl, "Command timeout (ms)", DEFAULTS.timeout);

  const autoToken = generateToken();
  const tokenInput = await ask(rl, "Bearer token (leave empty to auto-generate)", autoToken);
  config.token = tokenInput || autoToken;

  config.domain = await ask(rl, "Domain name (optional — for Caddy auto-HTTPS)", "");

  console.log(`\n  ${bold("── Generating config files ──")}\n`);

  // Write config files
  const { files, clientConfig } = await writeFiles(config, process.cwd());
  for (const f of files) {
    console.log(`  ${green("✔")} Created ${cyan(f.name)}`);
  }

  // ── PM2 setup ──
  console.log(`\n  ${bold("── Process management ──")}\n`);

  const wantPM2 = await askConfirm(rl, "Set up PM2 to auto-start the server?", true);
  let pm2Done = false;

  // Always create ecosystem.config.cjs (PM2-ready, always available)
  const ecoPath = resolve(process.cwd(), "ecosystem.config.cjs");
  await writeFile(ecoPath, buildEcosystem(config), "utf-8");
  console.log(`  ${green("✔")} Created ${cyan("ecosystem.config.cjs")}`);

  if (wantPM2) {
    // Ensure pm2 is available
    await tryExec("npm install -g pm2 2>nul || npm install -g pm2 2>/dev/null");

    const ok = await tryExec(`npx pm2 start ${ecoPath}`, { timeout: 15000 });
    if (ok) {
      await tryExec(`npx pm2 save`, { timeout: 10000 });
      pm2Done = true;
      console.log(`  ${green("✔")} Server started via ${cyan("PM2")}`);
    } else {
      console.log(`  ${yellow("⚠")} Could not auto-start PM2. Run manually:`);
      console.log(`     ${dim("npx pm2 start ecosystem.config.cjs")}\n`);
    }
  }

  // ── systemd (Linux only, and only if PM2 wasn't chosen) ──
  if (IS_LINUX && !wantPM2) {
    const wantSystemd = await askConfirm(rl, "Set up systemd service to auto-start the server?", false);
    if (wantSystemd) {
      const servicePath = resolve(process.cwd(), "mcp-shell-server.service");
      await writeFile(servicePath, buildSystemdService(config), "utf-8");
      console.log(`  ${green("✔")} Created ${cyan("mcp-shell-server.service")}`);

      console.log(`\n  ${yellow("To install the service, run as root:")}`);
      console.log(`     ${dim("sudo cp mcp-shell-server.service /etc/systemd/system/")}`);
      console.log(`     ${dim("sudo systemctl daemon-reload")}`);
      console.log(`     ${dim("sudo systemctl enable --now mcp-shell-server")}\n`);
    }
  }

  rl.close();
  return { config, clientConfig, pm2Done };
}

// ──────────────────────────────────────────────
//  CLI (non-interactive) mode
// ──────────────────────────────────────────────

async function cliSetup(opts) {
  const config = {
    port:    opts.port,
    workdir: resolve(opts.workdir),
    timeout: opts.timeout,
    token:   opts.token || generateToken(),
    domain:  opts.domain,
  };

  console.log(`  ${bold("meowshell — CLI Setup")}\n`);

  const { files, clientConfig } = await writeFiles(config, process.cwd());
  for (const f of files) {
    console.log(`  ${green("✔")} Created ${cyan(f.name)}`);
  }

  // Always create ecosystem.config.cjs (PM2-ready)
  const ecoPath = resolve(process.cwd(), "ecosystem.config.cjs");
  await writeFile(ecoPath, buildEcosystem(config), "utf-8");
  console.log(`  ${green("✔")} Created ${cyan("ecosystem.config.cjs")}`);

  // PM2 (unless skipped)
  let pm2Done = false;
  if (!opts.noPm2) {
    await tryExec("npm install -g pm2 2>nul || npm install -g pm2 2>/dev/null");

    const ok = await tryExec(`npx pm2 start ${ecoPath}`, { timeout: 15000 });
    if (ok) {
      await tryExec(`npx pm2 save`, { timeout: 10000 });
      pm2Done = true;
      console.log(`  ${green("✔")} Server started via ${cyan("PM2")}`);
    } else {
      console.log(`  ${yellow("⚠")} PM2 start failed. Run: npx pm2 start ecosystem.config.cjs\n`);
    }
  }

  return { config, clientConfig, pm2Done };
}

// ──────────────────────────────────────────────
//  Summary output
// ──────────────────────────────────────────────

function printSummary(config, clientConfig, pm2Done) {
  const protocol = config.domain ? "https (Caddy)" : "http";
  const host     = config.domain || "localhost";
  const url      = `${config.domain ? "https" : "http"}://${host}:${config.port}/mcp`;

  console.log(`\n  ${bold("╔══════════════════════════════════════════════════╗")}`);
  console.log(`  ${bold("║")}  All done! Here's your shiny new server.       ${bold("║")}`);
  console.log(`  ${bold("╚══════════════════════════════════════════════════╝")}\n`);
  console.log(`  ${cyan("Endpoint")}   ${url}`);
  console.log(`  ${cyan("Protocol")}   ${protocol}`);
  console.log(`  ${cyan("Workdir")}    ${config.workdir}`);
  console.log(`  ${cyan("Timeout")}    ${config.timeout}ms\n`);
  console.log(`  ${bold("Quick start:")}`);
  console.log(`  ${green("$")} ${dim("node meowshell.js")}`);
  if (pm2Done) {
    console.log(`  ${green("✔")} PM2 is running. ${dim("npx pm2 status")}`);
  }
  console.log(`\n  ${bold("Client config (paste into your MCP client):")}\n`);
  console.log(green(JSON.stringify(clientConfig, null, 2)));
  console.log(`\n  ${dim("Also saved to:")} ${cyan("mcp-client-config.json")}`);
  console.log(`  ${dim("Config file:")}   ${cyan(".env")}\n`);

  if (!config.domain) {
    console.log(`  ${yellow("💡 Tip:")} For remote access, set up a domain + Caddy for auto-HTTPS.`);
    console.log(`     Or run ${cyan("node setup.js")} again with ${cyan("--domain your.com")}\n`);
  } else if (!pm2Done) {
    console.log(`  ${yellow("💡 Tip:")} Keep the server alive with ${cyan("npx pm2 start ecosystem.config.cjs")}\n`);
  }
}

// ──────────────────────────────────────────────
//  Entry point
// ──────────────────────────────────────────────

async function main() {
  const opts = parseArgs(argv);

  let config, clientConfig, pm2Done;

  if (opts.interactive) {
    const result = await interactiveSetup();
    config = result.config;
    clientConfig = result.clientConfig;
    pm2Done = result.pm2Done;
  } else {
    const result = await cliSetup(opts);
    config = result.config;
    clientConfig = result.clientConfig;
    pm2Done = result.pm2Done;
  }

  printSummary(config, clientConfig, pm2Done);
}

main().catch((err) => {
  console.error(red("Setup failed:"), err);
  exit(1);
});
